"""Summarise results/threshold_flat_mlp.jsonl against FOCC-NN and apply the
pre-registered criterion (KBS/plan.md, 2026-09-19 12:00).

    python scripts/analyze_threshold.py          # report
    python scripts/analyze_threshold.py --latex  # table body for tab:threshold
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict

import numpy as np
from scipy.stats import wilcoxon

from _shared import RESULTS_DIR

from freqcascade import stats

DATASETS = [("reuters21578", "Reuters-21578"), ("litcovid", "LitCovid"), ("hoc", "HoC")]
ARMS = ["0.5 (stored)", "A global-tuned", "B per-label-tuned", "C recall-matched"]
ARM_TEX = {"0.5 (stored)": "Flat-MLP, $t{=}0.5$", "A global-tuned": "Flat-MLP, global $t$ (val.)",
           "B per-label-tuned": "Flat-MLP, per-label $t$ (val.)",
           "C recall-matched": "Flat-MLP, recall-matched $t$ (test)$^\\dagger$"}
METRICS = ["label_macro_f1", "bottom_quartile_label_recall", "micro_f1", "label_macro_recall"]


def _load():
    thr = defaultdict(dict)
    for x in (RESULTS_DIR / "threshold_flat_mlp.jsonl").read_text().splitlines():
        r = json.loads(x)
        thr[(r["dataset"], r["arm"])][r["fold"]] = r
    focc = {}
    for ds, _ in DATASETS:
        rows = [json.loads(x) for x in (RESULTS_DIR / f"{ds}.jsonl").read_text().splitlines() if x.strip()]
        focc[ds] = {r["fold"]: r for r in rows if r.get("method") == "FOCC-NN" and "error" not in r}
    return thr, focc


def _diff(focc, arm_rows, metric):
    f = sorted(set(focc) & set(arm_rows))
    return np.array([focc[i][metric] - arm_rows[i][metric] for i in f])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--latex", action="store_true")
    a = ap.parse_args()
    thr, focc = _load()
    present = [(d, n) for d, n in DATASETS if (d, ARMS[0]) in thr]

    if a.latex:
        print("%% generated by scripts/analyze_threshold.py --latex")
        for d, n in present:
            first = True
            for arm in ["FOCC-NN"] + ARMS:
                src = focc[d] if arm == "FOCC-NN" else thr[(d, arm)]
                vals = [np.mean([r[m] for r in src.values()]) for m in METRICS[:3]]
                cells = []
                for m, v in zip(METRICS[:3], vals):
                    if arm == "FOCC-NN":
                        cells.append("%.3f" % v)
                    else:
                        x = _diff(focc[d], src, m)
                        cells.append("%.3f (%+.3f)" % (v, -x.mean()))
                lab = "FOCC-NN" if arm == "FOCC-NN" else ARM_TEX[arm]
                head = ("\\multirow{5}*{%s}" % n) if first else ""
                print("%s & %s & %s \\\\" % (head, lab, " & ".join(cells)))
                first = False
            print("\\midrule")
        return

    for d, n in present:
        print(f"\n== {n}  (FOCC-NN: " + ", ".join(
            "%s %.4f" % (m, np.mean([r[m] for r in focc[d].values()])) for m in METRICS) + ")")
        for arm in ARMS:
            rows = thr[(d, arm)]
            ts = [r["threshold"] for r in rows.values() if r["threshold"] is not None]
            print(f"  {arm:20s} n={len(rows)}" + (f" t={np.mean(ts):.3f}" if ts else ""))
            for m in METRICS:
                x = _diff(focc[d], rows, m)
                p = wilcoxon(x).pvalue if np.any(x != 0) else 1.0
                print("    %-30s flat %.4f  FOCC-flat %+.4f  FOCC ahead %d/%d  p=%.4f"
                      % (m, np.mean([r[m] for r in rows.values()]), x.mean(), (x > 0).sum(), len(x), p))

    if len(present) < 3:
        print("\n(criterion needs all three corpora)")
        return
    print("\n== Pre-registered criterion")
    ps, wins = [], []
    for d, n in present:
        x = _diff(focc[d], thr[(d, "C recall-matched")], "bottom_quartile_label_recall")
        ps.append(wilcoxon(x).pvalue)
        wins.append(x.mean() > 0)
    adj = stats.holm_bonferroni(ps)
    ok = sum(1 for w, p in zip(wins, adj) if w and p < 0.05)
    for (d, n), w, p, q in zip(present, wins, ps, adj):
        print(f"  (C) {n:14s} FOCC bq-recall ahead={w}  raw p={p:.4f}  Holm p={q:.4f}")
    print(f"  -> FOCC's rare-label claim {'SURVIVES' if ok >= 2 else 'FAILS'} ({ok}/3 corpora)")
    for d, n in present:
        for arm in ("A global-tuned", "B per-label-tuned"):
            bq = _diff(focc[d], thr[(d, arm)], "bottom_quartile_label_recall").mean()
            f1 = _diff(focc[d], thr[(d, arm)], "label_macro_f1").mean()
            if bq <= 0 and f1 <= 0:
                print(f"  {n}: tuned flat MLP ({arm}) is level or ahead on BOTH bq recall and macro-F1")


if __name__ == "__main__":
    main()
